### PR TITLE
Some modifications to fit the kipoi specs

### PR DESCRIPTION
**Pull request by Karollus**
Dear Vikram,

With these modifications, it should run in kipoi. The test.ipynb notebook does a test run.

Note that for now I was not sure if Xpresso is stranded. I have made it so that it receives all sequences on the + strand. If it actually expects - strand sequences for - strand genes, we will need to slightly modify the dataloader to account for that.

Best,
Alex

### CODE REVIEW

**Comment by vagarwal87** [comment]
Hi Alex, 

Thank you for your help -- just wanted to check that currently, if it receives a sequence with BED coordinates mentioning '-' strand, then it will take the reverse complement of the extracted sequence before feeding it in, to reorient it? If so, that is the correct behavior I'm looking for.

**Comment by Karollus** [comment]
Unfortunately, the SeqInterval dataloader currently only gets from the + strand (it was designed for DNA models that do not care about strandedness). So if Xpresso requires the reverse complement, we will need to write a slightly adapted dataloader, which however should not be difficult, as most functionality already exists. I will make a prototype in the next few days.

**Comment by vagarwal87** [comment]
This plan sounds great, thanks for your help with this!

**Comment by Karollus** [comment]
Ok, now the strandedness should work as you described. The test notebook runs the model for chromosome 22, I hope the predictions are what they should be. 
If they are, I think everything is ready for integration into kipoi models

**Comment by vagarwal87** [comment]
Thanks for your help with this. I tested it on my full human promoter set on hg38 and got r^2 0.58. Looks like we can proceed as predictions seem to work fine.

**Pull request merged**
